### ISSUE TITLE
Help with getting access to /data directory

### ISSUE THREAD

**Issue by jaspreetishar** [maximilian-heeg/xenium-segmentation#2]
Hi, would you please be able to help get access to the xenium mock data?
https://github.com/maximilian-heeg/xenium-segmentation/blob/main/data

**Comment by maximilian-heeg** [comment]
Hi,
Unfortunately, I cannot share our mock dataset. This is a subset of a Xenium run in the lab that we did recently, and it has not been published. Any output from a Xenium run should work, however.
