### ISSUE TITLE
Cannot read project manifest properly

### ISSUE THREAD

**Issue by huanlity** [maximilian-heeg/xenium-segmentation#3]
Hi Thanks for creating this amazing tool. I am trying to run it through my Xenium data but having some issues at the moment, do you know how to fix it? Thank you. I changed the version to v.0.1.2 in the command but got the same error.

Best,
Huan Wang
Broad Institute

`(base) whuan@mcmicro-2021:~/store/segmentation_pipeline$ nextflow run maximilian-heeg/xenium-segmentaion -r v0.1.0 --xenium_path data/xenium_breast_normal
N E X T F L O W  ~  version 23.10.1
Pulling maximilian-heeg/xenium-segmentaion ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/maximilian-heeg/xenium-segmentaion/contents/nextflow.config?ref=v0.1.0
Remote resource not found: https://api.github.com/repos/maximilian-heeg/xenium-segmentaion/contents/main.nf?ref=v0.1.0`

**Comment by maximilian-heeg** [comment]
Hi,
here was a typo in the README. The command should say: `nextflow run maximilian-heeg/xenium-segmentation`. 
Best
Max

**Comment by huanlity** [comment]
@maximilian-heeg Thank you! Do you have recommendation on how to install singularity/apptainer, do I need to go through the whole thing on [this page](https://github.com/apptainer/apptainer/blob/main/INSTALL.md) or there is an easier way? Thanks! Huan.

**Comment by maximilian-heeg** [comment]
Since you are already in a conda environment, you could try this: https://anaconda.org/conda-forge/apptainer
