### ISSUE TITLE
Error with missing morphology_mip.ome.tif

### ISSUE THREAD

**Issue by kunleng** [maximilian-heeg/xenium-segmentation#5]
Hi Max, 

Thank you for making such a nice workflow for Xenium segmentation. I have some Xenium data generated from XOA v3.1.0.0 but the output folder seems to be missing the morphology_mip.ome.tif file, which based on the Xenium website does not seem to be generated automatically in XOA v3. Is there a way to run your workflow without the missing morphology_mip.ome.tif file? 

Best,
Kun 
UCSF

**Comment by maximilian-heeg** [comment]
Hi,
what error are you getting? With the multimodel segmentation kit, I had removed the custom DAPI segmentation and it should not rely on the `morphology_mip.ome.tif`. The pipeline only uses the `morphology_focus/morphology_focus_0000.ome.tif` for generating some of the plots at the end, but this is not a critical step.
Max

**Comment by kunleng** [comment]
Hi Max, thanks so much for the quick response! This is the error I'm getting: 

ERROR ~ Error executing process > 'NuclearSegmentation:getImageSize (1)'

Caused by:
  Process `NuclearSegmentation:getImageSize (1)` terminated with an error exit status (1)


Command executed:

  #!/usr/bin/env python
  import tifffile
  
  tif = tifffile.TiffFile('data/morphology_mip.ome.tif')
  page = tif.pages[0]  # get shape and dtype of image in first page
  pixel = page.shape[0] * page.shape[1]
  bytes = pixel * 16
  print(bytes)

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Traceback (most recent call last):
    File ".command.sh", line 4, in <module>
      tif = tifffile.TiffFile('data/morphology_mip.ome.tif')
    File "/usr/local/lib/python3.10/site-packages/tifffile/tifffile.py", line 4030, in __init__
      fh = FileHandle(file, mode=mode, name=name, offset=offset, size=size)
    File "/usr/local/lib/python3.10/site-packages/tifffile/tifffile.py", line 14118, in __init__
      self.open()
    File "/usr/local/lib/python3.10/site-packages/tifffile/tifffile.py", line 14137, in open
      self._fh = open(
  FileNotFoundError: [Errno 2] No such file or directory: '/home/kunleng/ParedesLab/Xenium_HPA/XeniumOutput/20241004/output-XETG00326__0034186__S21-5856-B2__20241004__203113/morphology_mip.ome.tif'

**Comment by kunleng** [comment]
Here's the full output from running the workflow: 

Launching `https://github.com/maximilian-heeg/xenium-segmentation` [pedantic_chandrasekhar] DSL2 - revision: cabad69255 [v0.1.2]


--------------------------------------------------------------------
   __   __          _                                              
   \ \ / /         (_)                                             
    \ V / ___ _ __  _ _   _ _ __ ___                               
     > < / _ \ '_ \| | | | | '_ ` _ \                              
    / . \  __/ | | | | |_| | | | | | |  _        _   _             
   /_/ \_\___|_| |_|_|\__,_|_| |_| |_| | |      | | (_)            
    ___  ___  __ _ _ __ ___   ___ _ __ | |_ __ _| |_ _  ___  _ __  
   / __|/ _ \/ _` | '_ ` _ \ / _ \ '_ \| __/ _` | __| |/ _ \| '_ \ 
   \__ \  __/ (_| | | | | | |  __/ | | | || (_| | |_| | (_) | | | |
   |___/\___|\__, |_| |_| |_|\___|_| |_|\__\__,_|\__|_|\___/|_| |_|
              __/ |                                                
             |___/  
--------------------------------------------------------------------
(c) Maximilian Heeg, 2023
https://github.com/maximilian-heeg/xenium-segmentation
--------------------------------------------------------------------

executor >  local (3)
[cb/3896d7] NuclearSegmentation:getImageSize (1) | 0 of 1
[-        ] NuclearSegmentation:cellpose         -
[fc/4cad6f] Baysor:BaysorConfig:create           | 1 of 1 ✔
[-        ] Baysor:tileXenium                    -
[-        ] Baysor:getNumberOfTranscripts        -
[-        ] Baysor:runBaysor                     -
[-        ] Baysor:mergeTiles                    -
[83/b69095] Report:dumpParameters                | 1 of 1 ✔
[-        ] Report:diagnostics                   -
[-        ] Report:evaluation                    -
[-        ] Report:scanpy                        -
[-        ] Report:boundaries                    -
[-        ] Report:build                         -
ERROR ~ Error executing process > 'NuclearSegmentation:getImageSize (1)'

Caused by:
  Process `NuclearSegmentation:getImageSize (1)` terminated with an error exit status (1)


Command executed:

  #!/usr/bin/env python
  import tifffile
  
  tif = tifffile.TiffFile('data/morphology_mip.ome.tif')
  page = tif.pages[0]  # get shape and dtype of image in first page
  pixel = page.shape[0] * page.shape[1]
  bytes = pixel * 16
  print(bytes)

Command exit status:
  1

Command output:
  (empty)

executor >  local (3)
[cb/3896d7] NuclearSegmentation:getImageSize (1) | 1 of 1, failed: 1 ✘
[-        ] NuclearSegmentation:cellpose         -
[fc/4cad6f] Baysor:BaysorConfig:create           | 1 of 1 ✔
[-        ] Baysor:tileXenium                    -
[-        ] Baysor:getNumberOfTranscripts        -
[-        ] Baysor:runBaysor                     -
[-        ] Baysor:mergeTiles                    -
[83/b69095] Report:dumpParameters                | 1 of 1 ✔
[-        ] Report:diagnostics                   -
[-        ] Report:evaluation                    -
[-        ] Report:scanpy                        -
[-        ] Report:boundaries                    -
[-        ] Report:build                         -
WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
ERROR ~ Error executing process > 'NuclearSegmentation:getImageSize (1)'

Caused by:
  Process `NuclearSegmentation:getImageSize (1)` terminated with an error exit status (1)


Command executed:

  #!/usr/bin/env python
  import tifffile
  
  tif = tifffile.TiffFile('data/morphology_mip.ome.tif')
  page = tif.pages[0]  # get shape and dtype of image in first page
  pixel = page.shape[0] * page.shape[1]
  bytes = pixel * 16
  print(bytes)

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Traceback (most recent call last):
    File ".command.sh", line 4, in <module>
      tif = tifffile.TiffFile('data/morphology_mip.ome.tif')
    File "/usr/local/lib/python3.10/site-packages/tifffile/tifffile.py", line 4030, in __init__
      fh = FileHandle(file, mode=mode, name=name, offset=offset, size=size)
    File "/usr/local/lib/python3.10/site-packages/tifffile/tifffile.py", line 14118, in __init__
      self.open()
    File "/usr/local/lib/python3.10/site-packages/tifffile/tifffile.py", line 14137, in open
      self._fh = open(
  FileNotFoundError: [Errno 2] No such file or directory: '/home/kunleng/ParedesLab/Xenium_HPA/XeniumOutput/20241004/output-XETG00326__0034186__S21-5856-B2__20241004__203113/morphology_mip.ome.tif'

Work dir:
  /home/kunleng/ParedesLab/Xenium_HPA/Segmentation/work/cb/3896d710d813a3c4a4c04bcf3d9366

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details

**Comment by maximilian-heeg** [comment]
I think you are still running an outdated version:
`nextflow run maximilian-heeg/xenium-segmentation -r v0.1.2 --xenium_path PATH_TO_XENIUM_OUTOUT`

The critical part is `-r v0.1.2` which corresponds to the [release/tag](https://github.com/maximilian-heeg/xenium-segmentation/releases). Try changing it to v0.3

Max

**Comment by kunleng** [comment]
Ahh okay gotcha! I think I just copied and pasted the example command from your GitHub, so would be great if you could update that for other users. Thanks so much for your help!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
