### ISSUE TITLE
Error from scanpy

### ISSUE THREAD

**Issue by hiraksarkar** [maximilian-heeg/xenium-segmentation#7]
Hi 
Thanks a lot for making it feasible to run Baysor on large files.
I am running the pipeline from server and encountering an error in the last step. I saved the log here https://gist.github.com/hiraksarkar/523834ba2457d6162c3a1dd9be0bd8d5. 

It seems the error comes from the script trying to load local scanpy, instead of using the container. Am I doing something wrong?

Best,

**Comment by maximilian-heeg** [comment]
Have you tried this?
https://github.com/maximilian-heeg/xenium-segmentation/?tab=readme-ov-file#troubleshooting

**Comment by hiraksarkar** [comment]
Hi @maximilian-heeg ,

The previous error was resolved, but now met with the alphashape not found error, should not this be part of the container? Or, do I need to change the config?


```
  ---------------------------------------------------------------------------
  ModuleNotFoundError                       Traceback (most recent call last)
  Cell In[1], line 11
        9 import tifffile
       10 import json
  ---> 11 from alphashape import alphashape
       12 from shapely.ops import transform
       13 warnings.filterwarnings('ignore')

  ModuleNotFoundError: No module named 'alphashape'

  INFO:    Cleaning up image...

Work dir:
  /n/fs/ragr-data/users/hirak/work/03/6402184272b6e7d6eba70c712e7c64

Container:
  /n/fs/ragr-data/users/hirak/work/singularity/maximilianheeg-docker-scanpy-v1.9.5_pyarrow.img

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
 ```

**Comment by maximilian-heeg** [comment]
I am sorry that you are having issues. Alphashape is in the docker container. See
https://github.com/maximilian-heeg/docker-scanpy/blob/main/requirements.txt

However, I am currently unfortunately unable to assist with troubleshooting. We made this pipeline available for others to use, but I do not have the bandwidth to provide support.

**Comment by maximilian-heeg** [comment]
It's public now. Will close the issue for now though.
